[params]
_merge = "deep"

username = "johndoe"
hostname = "example.com"
minTermsCount = 1

hasCJKLanguage = true

  [params.author]
    username = "cmj"
    hostname = "example.com"

  [[params.menu]]
    enabled = true
    name = "/dev/post"
    link = "/posts"

  [[params.menu]]
    enabled = true
    name = "/dev/tag"
    link = "/tags"
