[params]
_merge = "deep"

username = "johndoe"
hostname = "example.com"
minTermsCount = 1

toc = true

hasCJKLanguage = true

  [params.author]
    username = "cmj"
    hostname = "example.com"

  [params.hero]
    enabled = true
    icon = "user-secret"
